repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    - id: codespell

  - repo: local
    hooks:
      - id: sqlite-dump
        name: (TEST) sqlite dump
        description: simply dumps sqlite db into text.
        entry: sqlite_dump.sh
        language: script
        always_run: true
        args: [db, sdb, sqlite, db3, s3db, sqlite3, sl3, db2, s2db, sqlite2, sl2]
